---
- hosts: all
  become: true
  vars:
    vsftpd_anon_root: /srv/shares/public
    vsftpd_local_enable: true
    vsftpd_local_root: /srv/shares/private
    vsftpd_options:
      - key: delete_failed_uploads
        value: 'YES'
      - key: ftpd_banner
        value: "Welcome to the FTP service"
  roles:
    - role_under_test
  post_tasks:
    - name: Put a demo file in the anonymous directory
      copy:
        dest: '{{ vsftpd_anon_root }}/README'
        content: 'anon_root'
    - name: Put a demo file in the user directory
      copy:
        dest: '{{ vsftpd_local_root }}/README'
        content: 'local_root'
    - name: Add user for testing authenticated access
      user:
        name: alice
        state: present
        password: '$6$OfxvyTsMWVuj1rCY$GW689Q8mVlz8l/mMs1eX701xzOmL2doNlRLvjJ6tTrSgc5W/DTcBBZxqZZomEefX9puiRHtyCGI1HLd72hfQB1'
        # alice
